name: Auto Star Repository

on:
  push:
    branches:
      - main
      - master
  
  workflow_dispatch:

jobs:
  star-repo:
    runs-on: ubuntu-latest
    
    # यह सही किया गया हिस्सा है
    permissions:
      contents: write # 'stars: write' की जगह 'contents: write' का इस्तेमाल करें
      
    steps:
      - name: Star the repository
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/user/starred/${{ github.repository }}
