name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # ✅ Flutter version को सही किया गया है
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        # ✅ एक valid और stable version का इस्तेमाल करें
        flutter-version: '3.22.1'

    # ✅ Cache Flutter & Gradle dependencies
    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze project
      run: flutter analyze

    # ✅ Debug keystore generate karega (Firebase ke liye SHA keys milenge)
    - name: Create debug keystore
      run: |
        cd android/app
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,OU=Android,O=Android,L=Mountain View,ST=California,C=US"
        cd ../..

    # ✅ Debug APK banayega
    - name: Build Debug APK
      run: flutter build apk --debug

    # ✅ Artifact upload karega (GitHub Actions → build me download available hoga)
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk

    # ✅ Firebase ke liye SHA1 / SHA256 print karega
    - name: Print SHA1 / SHA256 Keys
      run: |
        cd android
        ./gradlew signingReport
