name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.1' # ✅ Dart 3.9.0

    # ✅ Cache Flutter & Gradle dependencies
    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze project
      run: flutter analyze

    - name: Create debug keystore
      run: |
        cd android/app
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000
        cd ../..

    - name: Build Debug APK
      run: flutter build apk --debug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: |
          build/app/outputs/flutter-apk/app-debug.apk
          build/app/outputs/apk/debug/app-debug.apk

    # ✅ SHA1 / SHA256 keys print karega (Firebase ke liye)
    - name: Print SHA1 / SHA256 Keys
      run: |
        cd android
        ./gradlew signingReport
